/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avp.valadofitnesshack.src.main;

import avp.valadofitnesshack.src.main.dataaccess.DataAccess;
import avp.valadofitnesshack.src.main.dto.Usuari;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Albert
 */
public class Main extends javax.swing.JFrame {

    private DataAccess da = new DataAccess();
    private javax.swing.JList<Usuari> lstUsuaris;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setSize(700,500);
        setLocationRelativeTo(null);
        
        lstUsuaris = new javax.swing.JList<>();
        jScrollPane2.setViewportView(lstUsuaris);
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsuarisValueChanged(evt);
            }
        });
        
        //lblIconLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsuaris = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuarisStrings = new javax.swing.JList<>();
        txtUserInfo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        btnUsuaris.setText("Usuaris");
        btnUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarisActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuaris);
        btnUsuaris.setBounds(6, 6, 72, 23);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(184, 227, 72, 23);

        lstUsuarisStrings.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUsuarisStrings.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsuarisStringsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsuarisStrings);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(6, 35, 103, 146);

        txtUserInfo.setText("jTextField1");
        jPanel1.add(txtUserInfo);
        txtUserInfo.setBounds(6, 193, 250, 22);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(127, 35, 129, 146);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarisActionPerformed
//        ArrayList<Usuari> usuaris = da.getUsuaris();
//        DefaultListModel dfm = new DefaultListModel<>();
//        for(Usuari u: usuaris){
//            dfm.addElement(u.toString());
//        }
//        lstUsuarisStrings.setModel(dfm);
          
    }//GEN-LAST:event_btnUsuarisActionPerformed

    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        DialogLogin dialogLogin = new DialogLogin(this, true, this);
        dialogLogin.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lstUsuarisValueChanged(javax.swing.event.ListSelectionEvent evt){
        Usuari selectedUser  = lstUsuaris.getSelectedValue();
        txtUserInfo.setText(selectedUser.getId() +": " +selectedUser);
    }
    private void lstUsuarisStringsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsuarisStringsValueChanged
        
    }//GEN-LAST:event_lstUsuarisStringsValueChanged
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUsuaris;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstUsuarisStrings;
    private javax.swing.JTextField txtUserInfo;
    // End of variables declaration//GEN-END:variables
}
