/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avp.valadofitnesshack.src.main;

import avp.valadofitnesshack.src.main.dataaccess.DataAccess;
import avp.valadofitnesshack.src.main.dto.Intent;
import avp.valadofitnesshack.src.main.dto.Usuari;
import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author Albert
 */
public class UserView extends javax.swing.JFrame {

    private DataAccess da = new DataAccess();
    private javax.swing.JList<Intent> lstAttemptsPendingReview;
    private javax.swing.JList<Usuari> lstUsuaris;
    private javax.swing.JList<String> lstVideos;
    
    private EmbeddedMediaPlayerComponent mediaPlayer;
    private JFileChooser fileChooser;
    private boolean isPlaying = false;
    
    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();
        setSize(700, 500);
        setLocationRelativeTo(null);
        
        lstAttemptsPendingReview = new javax.swing.JList<>();
        lstUsuaris = new javax.swing.JList<>();
        lstVideos = new javax.swing.JList<>();
        
        fileChooser = new JFileChooser();
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);
        
        
        lstAttemptsPendingReview.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAttemptsPendingReviewValueChanged(evt);
            }
        });
        
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsuarisValueChanged(evt);
            }
        });
        
        lstVideos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVideosValueChanged(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVideoPlayer = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtInfo = new javax.swing.JTextField();
        btnLogOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnGetAttemptsPendingReview = new javax.swing.JButton();
        btnGetUsers = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnPauseResumeVideo = new javax.swing.JButton();
        btnLoadFile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlVideoPlayer);
        pnlVideoPlayer.setBounds(260, 0, 434, 226);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtInfo)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(18, 316, 679, 54);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut);
        btnLogOut.setBounds(624, 376, 73, 23);

        jButton1.setText("Review");
        getContentPane().add(jButton1);
        jButton1.setBounds(18, 376, 72, 23);

        jButton2.setText("Edit");
        getContentPane().add(jButton2);
        jButton2.setBounds(102, 376, 72, 23);

        jButton3.setText("Delete");
        getContentPane().add(jButton3);
        jButton3.setBounds(186, 376, 72, 23);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 6, 239, 226);

        btnGetAttemptsPendingReview.setText("Get Attempts Pending Review");
        btnGetAttemptsPendingReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAttemptsPendingReviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetAttemptsPendingReview);
        btnGetAttemptsPendingReview.setBounds(6, 238, 187, 23);

        btnGetUsers.setText("Get Users Info");
        btnGetUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetUsers);
        btnGetUsers.setBounds(6, 267, 103, 23);

        jTextField1.setText("txtVideosPath");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(263, 267, 313, 22);

        btnPauseResumeVideo.setText("Pause/Resume");
        btnPauseResumeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseResumeVideoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPauseResumeVideo);
        btnPauseResumeVideo.setBounds(404, 238, 118, 23);

        btnLoadFile.setText("Load File");
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadFile);
        btnLoadFile.setBounds(263, 238, 123, 23);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnGetAttemptsPendingReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAttemptsPendingReviewActionPerformed
        jScrollPane1.setViewportView(lstAttemptsPendingReview);
        ArrayList<Intent> intents = da.getAttemptsPendingReview();
        DefaultListModel dfmu = new DefaultListModel<>();
        for (Intent i: intents){
            dfmu.addElement(i);
        }
        lstAttemptsPendingReview.removeAll();
        lstAttemptsPendingReview.setModel(dfmu);
    }//GEN-LAST:event_btnGetAttemptsPendingReviewActionPerformed

    private void btnGetUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetUsersActionPerformed
        jScrollPane1.setViewportView(lstUsuaris);
        ArrayList<Usuari> usuaris = da.getAllUsers();
          DefaultListModel dfmu = new DefaultListModel<>();
          for (Usuari u: usuaris){
              dfmu.addElement(u);
          }
          lstUsuaris.removeAll();
          lstUsuaris.setModel(dfmu);
    }//GEN-LAST:event_btnGetUsersActionPerformed

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        jScrollPane1.setViewportView(lstVideos);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION){
            jTextField1.setText(fileChooser.getSelectedFile().getAbsolutePath());
            File videosFolder = new File(fileChooser.getSelectedFile().getAbsolutePath());
            File[] videos = videosFolder.listFiles();
            DefaultListModel dlm = new DefaultListModel();
            for (int i=0; i<videos.length;i++){
                File video = new File(videos[i].getAbsolutePath());
                if(video.isFile()){
                    dlm.addElement(video.getName());
                }
            }
            lstVideos.removeAll();
            lstVideos.setModel(dlm);
        }
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void btnPauseResumeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseResumeVideoActionPerformed
        if(isPlaying){
            mediaPlayer.mediaPlayer().controls().pause();
            isPlaying = false;
            btnPauseResumeVideo.setText("Resume");
        }else {
            mediaPlayer.mediaPlayer().controls().start();
            isPlaying = true;
            btnPauseResumeVideo.setText("Pause");
        }
    }//GEN-LAST:event_btnPauseResumeVideoActionPerformed

    private void lstAttemptsPendingReviewValueChanged(javax.swing.event.ListSelectionEvent evt){
        Intent selectedIntent  = lstAttemptsPendingReview.getSelectedValue();
        txtInfo.setText(selectedIntent.getId() +": " +selectedIntent);
    }
    
    private void lstUsuarisValueChanged(javax.swing.event.ListSelectionEvent evt){
        Usuari selectedUser  = lstUsuaris.getSelectedValue();
        txtInfo.setText(selectedUser.getId() +": " +selectedUser);
    }
    
    private void lstVideosValueChanged(javax.swing.event.ListSelectionEvent evt){
        if(evt.getValueIsAdjusting()){
            return;
        }
        String videoFileFolder = fileChooser.getSelectedFile().getAbsolutePath();
        String videoFileAbsolutePath = videoFileFolder +"\\" + lstVideos.getSelectedValue();
        mediaPlayer.mediaPlayer().media().play(videoFileAbsolutePath);
        isPlaying = true;
        btnPauseResumeVideo.setText("Pause");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetAttemptsPendingReview;
    private javax.swing.JButton btnGetUsers;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPauseResumeVideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlVideoPlayer;
    private javax.swing.JTextField txtInfo;
    // End of variables declaration//GEN-END:variables
}
